version: "3"
services:
  qmk:
    image: qmk_test
    build: .
    stdin_open: true
    volumes:
      - ./keymap/.:/qmk_firmware/keyboards/${KEYBOARD}/keymaps/awesome/
      - ./hex/:/qmk_firmware/hex/
    environment:
      - KEYBOARD=${KEYBOARD}
      - KEYMAP=${KEYMAP}